spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useOldAliasMetadataBehavior=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 5 #连接池最小
      max-active: 20  #连接池最大
      max-wait: 6000  #等待连接超时时间
      time-between-eviction-runs-millis: 6000 #检测需要关闭空闲连接的间隔时间
      min-evictable-idle-time-millis: 60000  #连接最小生存时间
      max-evictable-idle-time-millis: 300000  #连接最大生存时间
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true #打开PSCache，并且指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j#配置监控统计拦截的filters，stat去掉后监控界面sql无法统计，'wall'用于防火墙
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      use-global-data-source-stat: true #合并多个DruidDataSource的监控数据
      aop-patterns: com.cht.*.service.*
      stat-view-servlet:
        enabled: true
        login-username: admin #监控页面登录用户名  
        login-password: admin #监控页面登录密码 
  resources:
    static-locations: classpath:/static/
  mvc:
    view:
      prefix: /WEB-INF/jsp/ #设置视图前缀
      suffix: .jsp # 设置视图后缀
  jpa:
    show-sql: true


server:
  port: 8080
  context-path: /data
  connection-timeout: 10000  #设置超时时间
#  address: 127.0.0.2  #设置服务地址

  



